server:
  port: 8888

spring:
  security:
    user:
      name: user
      password: s3cr3t
  cloud:
    config:
      server:
        native:
          search-locations: file:///D:/Projects/Java/config-server/config
  profiles:
    active: native